# config.yaml 

# paths to files
aligned_fasta_fullseq: "aligned_LSU.fasta"
updateannotated_fasta_output: "updated_annotated80relabunfullseq.fasta"
blast_results_file: "blast_results.txt"
annotated_fasta_fullseq: "annotated80relabunfullseq.fasta"
processed_blast_output: "processed_unite_results.csv"
eightyfungal_fasta: "80relabundITS.fasta"
nonduplicate_ITSx: "Atnarova.ITS2nondup.fasta"
fungalITSx_file: "Atnarova.ITS2.fasta"
itsx_output_prefix: "Atnarova"
scatafastaclusters_file: "data/all_clusters_scata6384.fasta"
labels_file: "data/tagnames-Atnarova.txt"
unite_results_file: "unknowns.txt"
selectedduplicate: "selectedduplicate.fasta"
duplicate: "duplicate.fasta"
scata_file: "data/all_clusters_scata6384.txt"

